[build]
  base = "client"
  command = "npm install && npm run build"
  publish = "web-build"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
