services:
  - type: web
    name: loveliberia-server
    env: node
    build:
      npm install
      npm run build
    start: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://fredisaac2012:ATvCCwKBqBtRKAfE@cluster0.1ukcfz2.mongodb.net/loveliberia?retryWrites=true&w=majority&appName=Cluster0
      - key: PORT
        value: ${PORT}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: NODE_ENV
        value: production
      - key: SOCKET_IO_PORT
        value: ${SOCKET_IO_PORT}

databases:
  - name: loveliberia-db
    databaseName: loveliberia
    user: loveliberia-user
