services:
  - type: web
    name: loveliberia-server
    env: node
    build:
      npm install
      npm run build
    start: npm start
    envVars:
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: PORT
        value: ${PORT}
      - key: JWT_SECRET
        value: ${JWT_SECRET}

databases:
  - name: loveliberia-db
    databaseName: loveliberia
    user: loveliberia-user
