services:
  - type: web
    name: loveliberia-server
    env: node
    build:
      npm install
      npm run build
    start: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://fredisaac2012:ATvCCwKBqBtRKAfE@cluster0.1ukcfz2.mongodb.net/loveliberia?retryWrites=true&w=majority&appName=Cluster0
      - key: PORT
        value: ${PORT}
      - key: JWT_SECRET
        value: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6A7B8C9D0E1F2G3H4I5J6K7L8M9N0O1P2Q3R4S5T6U7V8W9X0Y1Z2"
      - key: NODE_ENV
        value: production
      - key: SOCKET_IO_PORT
        value: ${SOCKET_IO_PORT}

databases:
  - name: loveliberia-db
    databaseName: loveliberia
    user: loveliberia-user
